### ISSUE TITLE
TypeError: 'MultiPolygon' object is not iterable

### ISSUE THREAD

**Issue by pinecho** [chenhaoxing/DiffusionInst#4]
Hi, first thanks for your great work.

There is a TypeError when I tried to run your code:
```
ERROR [ d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/detectron2/engine/train_loop.py", line 268, in run_step
    data = next(self._data_loader_iter)
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/detectron2/data/common.py", line 234, in __iter__
    for d in self.dataset:
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/detectron2/data/common.py", line 201, in __iter__
    yield self.dataset[idx]
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/detectron2/data/common.py", line 90, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/home/abc/Projects/DiffusionInst/diffusioninst/dataset_mapper.py", line 130, in __call__
    annos = [
  File "/home/abc/Projects/DiffusionInst/diffusioninst/dataset_mapper.py", line 131, in <listcomp>
    utils.transform_instance_annotations(obj, transforms, image_shape)
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/detectron2/data/detection_utils.py", line 297, in transform_instance_annotations
    p.reshape(-1) for p in transforms.apply_polygons(polygons)
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/fvcore/transforms/transform.py", line 297, in <lambda>
    return lambda x: self._apply(x, name)
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/fvcore/transforms/transform.py", line 291, in _apply
    x = getattr(t, meth)(x)
  File "/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/fvcore/transforms/transform.py", line 724, in apply_polygons
    for poly in cropped:
TypeError: 'MultiPolygon' object is not iterable
```

Could you please tell me if there is any solution?
Thanks

**Comment by zhangxgu** [comment]
@pinecho 
Hi, I start a new project file by git clone our code and can run it with batch size 2 on one gpu
`CUDA_VISIBLE_DEVICES=3 python train_net.py --num-gpus 1  --config-file configs/diffinst.coco.res50.inst.yaml  OUTPUT_DIR /data2/`
![image](https://user-images.githubusercontent.com/20377534/207572992-6db1b714-a6a2-42e1-a222-6190e2a1750b.png)

Maybe the error is from pytorch or cuda version?

**Comment by pinecho** [comment]
Thanks, I would check the environment.

**Comment by pinecho** [comment]
@zhangxgu 
Hi, may I ask about the version of `shapely` in your project?
I noticed that a warning related to it may cause the above error:
```
[12/14 16:17:58 d2.engine.train_loop]: Starting training from iteration 0
/home/abc/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/shapely/set_operations.py:133: RuntimeWarning: invalid value encountered in intersection
  return lib.intersection(a, b, **kwargs)
```
Thank you.

**Comment by pinecho** [comment]
Updating the `fvcore` to the latest version solved the problem, thanks.
